# Workflow for macOS (latest).
name: Test

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - '**.md'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest
    # We want to run on external PRs, but not on our own internal PRs as
    # they'll be run by the push to the branch
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'ArthurBandaryk/push-pull'

    steps:
      # Checkout the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v1

      - name: Check for bazel
        run: bazel --version
